### ISSUE TITLE
CPP Port

### ISSUE THREAD

**Issue by dimitrijejankov** [Gnurfos/transvoxel_rs#1]
Hey, I spent the weekend porting your library to C++. Hope you don't mind. It is a bit of a clumsy port. I added a reference back you the original.

https://github.com/dimitrijejankov/transvoxel_cpp

**Comment by Gnurfos** [comment]
Hi, thanks for notifying me. I don't mind at all, it's not my algorithm anyway. I'm glad my implementation can be useful to someone.

I hope you do something nice with. Let me know if you do, or if you find bugs, and also if you come up with the need to improve the interface.
