### ISSUE TITLE
New Feature: Include weights to triangle calculation

### ISSUE THREAD

**Issue by davids91** [Gnurfos/transvoxel_rs#5]
The triangle vertex positions could be interpolated between the cells they are in between.

By interpolation I mean like this: 
https://cs.stackexchange.com/questions/71102/interpolation-on-marching-cubes-algorithm 
https://computergraphics.stackexchange.com/questions/9899/2d-metaballs-with-marching-squares-and-linear-interpolation

**Comment by Gnurfos** [comment]
If I understand correctly, I'd say this is done:

See https://github.com/Gnurfos/transvoxel_rs/blob/main/src/density.rs#L99

The emitted vertex is not systematically in the middle of the cube edge.
